
//wonder what'll happen if I toss Realm667 ZSCRIPT shit down here lol
//Death Incarnate boss
//Monster-Death Incarnate
Class Incarnate : Actor
{
  Default
  {
    Health 8000;
    Radius 20;
    Height 56;
    Mass 500;
    Speed 12;
    PainChance 64;
    Damagefactor "IncarnateShot", 0;
    Obituary "%o was killed by Death Incarnate's glare.";
    HitObituary "%o was beaten to death by Death Incarnate.";
    SeeSound "monster/incsit";
    PainSound "skeleton/pain";
    DeathSound "monster/incdth";
    ActiveSound "monster/incact";
    AttackSound "monster/incatk";
    MONSTER;
	+BOSS
    +FLOORCLIP
    +SHORTMISSILERANGE
    +DONTHARMCLASS
    // [MagicWazard] Note to modders: adding a GibHealth value of 50 - 100 will make
    // it easier to trigger his Hades Sphere-spawning XDeath sequence
  }

  States
  {
  Spawn:
    INCA AB 10 A_Look();
    Loop;
  See:
    INCA AABBCCDDEEFF 2 A_Chase();
    Loop;
  Melee:
    INCA G 0 A_Jump(128, "Melee2");
    INCA G 0 A_FaceTarget();
    INCA G 6 A_SkelWhoosh();
    INCA H 6 A_FaceTarget();
    INCA I 6 A_CustomMeleeAttack(7*random(1,8), "monster/inchit");
    Goto See;
  Melee2:
    INCA R 0 A_FaceTarget();
    INCA R 5 A_SkelWhoosh();
    INCA S 5 A_FaceTarget();
    INCA T 5 A_CustomMeleeAttack(7*random(1,8), "monster/inchit");
    INCA G 0 A_FaceTarget();
    INCA G 5 A_SkelWhoosh();
    INCA H 5 A_FaceTarget();
    INCA I 5 A_CustomMeleeAttack(7*random(1,8), "monster/inchit");
    Goto See;
  Missile:
    INCA J 5 A_FaceTarget();
    INCA J 5;
    INCA U 10 Bright A_CustomBulletAttack(30,0,5,3,"DIpuff",1024);
    INCA K 10;
    Goto See;
  Pain:
    INCA L 5;
    INCA L 5 A_Pain();
    Goto See;
  Death:
    INCA L 0 A_Jump(192, "Death2");
    INCA LM 7;
    INCA N 7 A_Scream();
    INCA O 7 A_NoBlocking();
    INCA P 7;
    INCA Q -1;
    Stop;
  Death2: //Can revive
    INCA LM 7;
    INCA N 7 A_Scream();
    INCA O 7 A_NoBlocking();
    INCA P 7;
    INCA Q 0 A_Jump(192,4);
    INCA Q 0 A_Jump(128,4);
    INCA Q 0 A_Jump(96,4);
    INCA Q 0 A_Jump(64,4);
    INCA Q 115;
    INCA Q 115;
    INCA Q 115;
    INCA Q 115;
    INCA Q 115;
    INCA Q -1 Thing_Raise(0);
    Stop;
  XDeath:
    INCX A 10 Bright A_Playsound("monster/incexp");
    INCX BC 5 Bright;
    INCX D 5 Bright A_NoBlocking();
    INCX D 0 Bright A_SpawnItem("HS",0,32);
    INCX EFGHIJ 5 Bright;
    INCX K -1;
  Raise:
    INCA Q 0 A_KillChildren();
    INCA QPONML 5;
    Goto See;
  }
}


//new visible puff
Class DIPuff : Actor
{
  Default
  {
    RENDERSTYLE "Add";
    DamageType "IncarnateShot";
    +NOBLOCKMAP;
    +NOGRAVITY;
    +RANDOMIZE;
    +PUFFONACTORS;
  }

  States
  {
  Spawn:
    INPF ABCDE 3 Bright;
    Stop;
  }
}


//old invisible puff
/*Class DIPuff : actor
{
  Default
  {
    Radius 0;
    Height 1;
    Speed 0;
    RENDERSTYLE "NONE";
    DamageType "IncarnateShot";
    PROJECTILE;
  }

  States
  {
  Spawn:
    TNT1 A 2 Bright;
    Stop;
  }
}*/
//End of Incarnate


